/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jsrr */

#ifndef _Included_Jsrr
#define _Included_Jsrr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jsrr
 * Method:    init
 * Signature: (Ljava/lang/String;IZZD)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_Jsrr_init
  (JNIEnv *, jclass, jstring, jint, jboolean, jboolean, jdouble);

/*
 * Class:     Jsrr
 * Method:    close
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jsrr_close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Jsrr
 * Method:    get_msg_ptr
 * Signature: (Ljava/lang/Object;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_Jsrr_get_1msg_1ptr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Jsrr
 * Method:    get_length_ptr
 * Signature: (Ljava/lang/Object;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_Jsrr_get_1length_1ptr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Jsrr
 * Method:    send
 * Signature: (Ljava/lang/Object;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jsrr_send
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     Jsrr
 * Method:    receive
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jsrr_receive
  (JNIEnv *, jclass, jobject);

/*
 * Class:     Jsrr
 * Method:    reply
 * Signature: (Ljava/lang/Object;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jsrr_reply
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
