/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libsrr_srr */

#ifndef _Included_libsrr_srr
#define _Included_libsrr_srr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libsrr_srr
 * Method:    init
 * Signature: (Ljava/lang/String;IZZD)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_libsrr_srr_init
  (JNIEnv *, jclass, jstring, jint, jboolean, jboolean, jdouble);

/*
 * Class:     libsrr_srr
 * Method:    close
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libsrr_srr_close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     libsrr_srr
 * Method:    get_msg_ptr
 * Signature: (Ljava/lang/Object;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_libsrr_srr_get_1msg_1ptr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     libsrr_srr
 * Method:    get_length_ptr
 * Signature: (Ljava/lang/Object;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_libsrr_srr_get_1length_1ptr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     libsrr_srr
 * Method:    send
 * Signature: (Ljava/lang/Object;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libsrr_srr_send
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     libsrr_srr
 * Method:    receive
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libsrr_srr_receive
  (JNIEnv *, jclass, jobject);

/*
 * Class:     libsrr_srr
 * Method:    reply
 * Signature: (Ljava/lang/Object;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libsrr_srr_reply
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
